name: Run Flask App

on:
  push:
    branches:
      - main  # Pastikan untuk mengganti ini dengan branch yang relevan

jobs:
  build-and-run-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install gunicorn  # Install Gunicorn untuk server WSGI

    - name: Run Flask app
      run: |
        source venv/bin/activate
        gunicorn --bind 0.0.0.0:5000 app6:app  # Menjalankan Flask menggunakan Gunicorn
